nipy/nipy

.travis.yml
nipy/algorithms/statistics/tests/test_utils.py
nipy/algorithms/utils/tests/test_matrices.py

There were two test failures that break the build. I believe the fixes I made are correct:
* Use numpy's `assert_array_almost_equal` instead of `assert_almost_equal` on a 3D array.
* matrix rank should be the same (10) whether tolerance is +/- eps
It'd be great to get this merged in, looks like Python 2.x build has been broken for some time.

Fixing tests

---

nipy/algorithms/utils/tests/test_matrices.py

Test was testing if increasing the threshold resulted in lower matrix rank
scores.  This was the right test, but we were using numpy.linalg.svd to get
the eigenvalues, rather than scipy.linalg.svd, so the values were slightly
different from the ones seen inside the tested routine, and the test was
failing.

BF: restore and fix original matrix rank test

---

nipy/tests/scriptrunner.py
nipy/tests/test_scripts.py

Use scriptrunner module that started off in the delocate project. Well, it
started in the test_scripts.py module here, but I refactored it in the
delocate project, and the refactoring is coming back home.

RF: move scriptrunner code into own module

---

nipy/algorithms/statistics/formula/formulae.py
nipy/algorithms/statistics/formula/tests/test_formula.py

Closes gh-258.
Intermittent errors testing Formula, turned out to be from:
* An error I introduced trying to make it easier to use sub-classes with
Formula add and subtract;
* Unpredictable order of terms after subtraction, caused by use of set to find
unique terms.

MRG: fix intermittent errors from Formula

---

README.rst

We got an email to nipy-devel this morning. I thought I'd update the mailing list metadata to what I believe is the current recommendations.

Update mailing list info

---

nipy/labs/viz_tools/maps_3d.py

This is a general fix for #325 . In the newest version of `numpy`, when `diag` returns a vector of numbers along the diagonal, that vector is read-only. In places where we wish to manipulate the elements of that vector, we need to call `copy()` first.
I manually went through to check each call to `diag`, and to see where we manipulated the elements or returned the vector value.
**Questions:**
* Do we have tests that use `numpy==1.9`? 
* Do we want to add a specific plotting regression for #325?

diag = >diag.copy() when the matrix will be manipulated.

---

nipy/algorithms/diagnostics/screens.py

We were using the axis number of the PCA analysis (usually axis index 3, time)
as the number of components (by default, 10).  Fix.
I've tested this at the command line with matplotlib, but it's hard to test
automatically without doing some image comparison test, and that seems like a
lot of work.

BF: fix bug in writing PCA time-courses

---

nipy/modalities/fmri/experimental_paradigm.py
nipy/modalities/fmri/tests/test_paradigm.py

Addresses issue https://github.com/nipy/nipy/issues/310

Clean paradigm

---

Makefile
README.rst
doc/devel/guidelines/make_release.rst
nipy/info.py
tools/refresh_readme.py

Rewrite long description, with correct dependencies.
Port over the nibabel machinery for filling the README.rst file from the
long description.
Note this in the release notes.

MAINT: rewrite long description; fill README.rst

---

nipy/modalities/fmri/tests/test_utils.py
nipy/modalities/fmri/utils.py

I'm trying to work out a good interface to express the fact that generally,
when we convolve things with HRFs, we want the same interval for the kernel,
and the same dt.
Maybe we could have an HRF object, that has a 'convolve' method, maybe an
'evaluate' method (to evaluation the real function at given time values, and a
`symfunc` property for the symbolic function.
I haven't really thought this last part through.

MRG: thinking of an interface for HRF convolution

---

.travis.yml
nipy/algorithms/interpolation.py
nipy/algorithms/registration/resample.py
nipy/algorithms/resample.py
nipy/algorithms/tests/test_resample.py
nipy/fixes/scipy/__init__.py
nipy/fixes/scipy/ndimage/__init__.py
nipy/fixes/setup.py
nipy/info.py

Scipy ndimage, at least for scipy 0.9.0, fails when trying to interpolate data
of type np.intp, on a 32-bit system we are testing on:
http://nipy.bic.berkeley.edu/builders/nipy-py2.6-32/builds/291/steps/shell_6/logs/stdio
The interpolation failure gives an error like this:
```
File "/usr/lib/python2.7/dist-packages/scipy/ndimage/interpolation.py", line 392, in affine_transform
output, order, mode, cval, None, None)
RuntimeError: data type not supported
```
In fact, the numpy types np.int32 and np.intp (on 32-bits) are the same 32-bit
signed integer types, so we can just view the data as np.int32 (on 32 bits)
before running the ndimage routines.
Write wrappers around `affine_transform` and `map_coordinates` to do this
conversion, and extend tests.
The tests raise some errors on very old …

MRG: hack to work round np.intp bug in ndimage

---

nipy/algorithms/registration/scripting.py
nipy/algorithms/registration/tests/test_scripting.py

A rewrite and extension of the PR https://github.com/nipy/nipy/pull/317
Adds more general handling of affine, writing of the TR into the affine, and
more general handling of filenames with dots in them.

MRG: rewritten, extended fix for reg script affine

---

nipy/algorithms/group/parcel_analysis.py

This hopefully fixes https://github.com/nipy/nipy/issues/358
The way I had implemented the `_gaussian_energy` routine in parcel analysis was actually quite stupid as I was not exploiting kernel separability, and was therefore requesting quite a lot of memory, occasionally triggering memory errors.

Save memory in parcel analysis

---

nipy/algorithms/statistics/empirical_pvalue.py

Numpy 1.10 seems to need an integer input to np.histogram.
Probably fixes gh-369.
I would be happy of a quick review.

BF: make histogram bins integer for numpy 1.10

---

.travis.yml
MANIFEST.in
nipy/info.py
nipy/setup.py
requirements.txt
setup.py
setup_helpers.py

python setup.py sdist was broken, because I wasn't adding some files to the
MANIFEST.in, and because I wasn't correctly using the numpy build_py command.
In other news, it was annoying to have to install sympy etc to run python
setup.py egg_info, which was in turn required when installing via pip - see
gh-320.
Fix both of these by dropping checks for Mayavi and Cython, dropping
nibabel/nisext dependency (by copying code and refactoring), and letting
setuptools take care of dependency checking for missing packages.

MRG: refactoring setup.py to fix sdist etc

---

nipy/algorithms/statistics/models/tests/test_olsR.py

due to bug in numpy
Related: https://github.com/numpy/numpy/issues/5200

test_olsR: use assert_array_almost_equal instead

---

scripts/nipy_3dto4d
scripts/nipy_4d_realign
scripts/nipy_4dto3d
scripts/nipy_diagnose
scripts/nipy_tsdiffana

Shebang lines should be "!python" in order for setuptools / pip to
rewrite the shebangs when installing.
Fixes errors on Python 3.5 e.g.
http://nipy.bic.berkeley.edu/builders/nipy-bdist32-35/builds/6/steps/shell_10/logs/stdio

BF: fix shebang lines for scripts

---

setup_helpers.py

A bug in the setup_helpers where I was not returning the error
message when we can't get the version of a package we need.

BF: fix error message return for missing version

---

.travis.yml
nipy/algorithms/statistics/models/nlsmodel.py
nipy/algorithms/statistics/models/regression.py
nipy/algorithms/utils/pca.py
nipy/modalities/fmri/fmristat/model.py

This is an alternative to #394.  In this PR, we switch from using
scipy.linalg.pinv to using numpy.linalg.pinv, on the basis that, at least as of
scipy 0.17, numpy pinv is more accurate, as measured by least squares sum of
squared errors.
This fixes the test failure we were getting from scipy 0.17 without the need to
relax the precision threshold (#394).
Of course, this PR might cause subtle changes in results.  On the other hand,
that will likely be true for scipy 0.17 compared to scipy 0.16 without this
change.

MRG: prefer numpy pinv to scipy pinv

---

nipy/modalities/fmri/fmristat/hrf.py
nipy/modalities/fmri/tests/test_utils.py
nipy/modalities/fmri/utils.py

Closes gh-395.
See https://github.com/sympy/sympy/pull/10874 for a detailed description of the problem and merged sympy PR.

MRG: fix error using interp1d in sympy 1.0

---

nipy/modalities/fmri/design.py
nipy/modalities/fmri/tests/test_design.py

Allow stacking empty designs, designs that are just arrays.  This makes
fits what the docstring describes, and is a little easier to use.

RF+TST: refactor design stacking for generality

---

nipy/algorithms/statistics/mixed_effects_stat.py

[MRG] fixed failing doctest

---

nipy/algorithms/statistics/tests/test_intrinsic_volumes.py

32-bit giving test precision error::
line 154, in test_mu2tet
assert_equal(intvol.mu2_tet(0,0,0,0,1,0,0,1,0,1), (3./2 +
np.sqrt(3./4))/2)
AssertionError: 1.1830127018922194 != 1.1830127018922192
See: https://travis-ci.org/MacPython/nipy-wheels/jobs/140268243#L451

TST: relax test precision a little for 32-bit

---

nipy/algorithms/registration/groupwise_registration.py
nipy/algorithms/registration/tests/test_fmri_realign4d.py

with "fail-safe" caveats. addressing https://github.com/nipy/nipy/issues/409

Realign4d TR from header

---

nipy/io/tests/test_image_io.py

NB not sure how this one escaped my testing of dependents when checking one of nibabel rcs
need it now to resole FTBFS on debians https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=836538

BF: allow for generic IOError-based exception to be thrown when loading non existing file

---

nipy/algorithms/registration/scripting.py

Scripting module doing unconditional import of matplotlib.pyplot,
triggering problems where the chosen backend is not present.  Delay
import until using for plotting.
Maybe closes gh-414.

RF: only import matplotlib if plotting

---

nipy/algorithms/clustering/tests/test_imm.py

Allow for occasional failure due to variation in random number output.
Closes #418.

TST: relax imm test threshold

---

nipy/labs/spatial_models/mroi.py
nipy/labs/spatial_models/tests/test_mroi.py

Rename variables for clarity, as proposed in
https://github.com/nipy/nipy/pull/422

RF: rename variables in ROI selection loops

---

nipy/algorithms/statistics/rft.py
nipy/algorithms/statistics/tests/test_rft.py

New numpy returns a copy of the polynomial coefficients from poly.c,
rather than the actual coefficent array, so when we were modifying the
polynomial coefficients, the polynomial object wasn't seeing our
changes, leading to errors in the RFT module - see e.g.
https://nipy.bic.berkeley.edu/builders/nipy-py2.7-osx-10.10/builds/52/steps/shell_9/logs/stdio
Numpy issue raised on numpy-discussion mailing list.

MRG: new numpy protects polynomial coefficients

---

tools/nicythize

Make nicythize work for fff.pxd includes, and with Python 3.
[skip ci]

MRG: update nicythize for Python 3; add includes

---

nipy/modalities/fmri/hrf.py
nipy/modalities/fmri/tests/test_utils.py
nipy/modalities/fmri/utils.py

sympy 1.6 introduced breaking change (see
https://github.com/sympy/sympy/wiki/Release-Notes-for-1.6 for full log):
Relational is no longer a subclass of Expr and does not produce nonsensical
results in arithmetic operations. This affects all Relational subclasses (Eq,
Ne, Gt, Ge, Lt, Le). It is no longer possible to call meaningless Expr methods
like as_coeff_Mul on Relational instances. (#18053 by @oscarbenjamin)
which broke all Pythonish expressions like `(x > 0) * (x < 1)` to define a square
wave.  Thanks to guidance from @oscarbenjamin in
https://github.com/sympy/sympy/issues/20981 I RFed all such uses to use
sympy.Piecewise instead to make it more explicit.
While at it, I also adjusted comments claiming intervals like `[0, 1]` (which
includes the endpoints), whenever in reality they …

BF: avoid relying on Pythonic casting of bool into numeric for sympy expressions

---

setup.py
setup_helpers.py

Give in and always use setuptools.
Drop support routines for avoiding setuptools.
Always specify numpy and scipy dependency.
Closes #472

RF: rely on setuptools, drop setup.py heroics

---

.travis.yml
nipy/info.py

Minima as of about October 2017.
Attempt to fix some new failures using Piecewise, which boil down to:
```python
import sympy
t = sympy.symbols('t')
f1 = sympy.Piecewise((0, t <= 0), (1, t < 1), (0, True))
ff = sympy.lambdify('t', f1, "numpy")(0)
```
This gives an error where "iff" is not defined, for Sympy 0.7.0.

MAINT: update minimum requirements

---

examples/interfaces/process_ds105.py
examples/interfaces/process_fiac.py
nipy/algorithms/utils/pca.py
nipy/algorithms/utils/tests/test_pca.py
nipy/core/reference/coordinate_map.py
nipy/core/reference/coordinate_system.py
nipy/core/reference/tests/test_coordinate_map.py
nipy/core/reference/tests/test_coordinate_system.py

Apparently "object" is identical in behavior.

MRG: remove deprecated use of np.object

---

nipy/modalities/fmri/design.py
nipy/utils/tests/test_utilities.py

As of Numpy 1.20, np.prod calls the __array__ method of input objects,
and this messes up Formula products.  Adapt and use basic sequence
product instead.

BF: change in np.prod upsets Formulae

---

nipy/algorithms/interpolation.py
nipy/algorithms/kernel_smooth.py
nipy/algorithms/tests/test_interpolator.py

Scipy >= 1.6.0 not longer guarantees that you get the same result when
interpolating directly (with map_coordinates, prefilter=True - the default) and
when using pre-calculated filters (map_coordinates, prefilter=False).
Therefore, we have to pad the calculated filter to get the same result.
See:
* https://github.com/nipy/nipy/issues/468
* https://github.com/scipy/scipy/issues/13600

MRG: fix new interpolation errors with Scipy 1.6

---

nipy/algorithms/interpolation.py
nipy/algorithms/tests/test_interpolator.py

Extend testing of prefiltered interpolation.
This revealed various bugs:
* Prefiltering=False of linear interpolation was failing, because the
prefilter=False option didn't make sense - because we were (correctly)
not prefiltering.
* Use more standard TemporaryFile for backing store to avoid errors from
too many open files.
* Avoid padding before prefiltering for Scipy < 1.6, because this gives
different results from non-prefiltered case.
Also see #478

MRG: Extend testing, fix / simplify interpolation

---

nipy/labs/viz_tools/cm.py

Matplotlib removed the `revcmap` function in 3.4, just released.
Rewrite using the `reversed` method of the colormap.
I'd love a review here.  Is there anyone out there who uses `labs.viz` that can
test this?

MRG: Fix for loss of revcmap in Matplotlib 3.4

---

pyproject.toml
setup.py

Pip uses build isolation by default. This adds a `pyproject.toml` to declare the build-time dependencies. It also tweaks the `sys.path` in `setup.py` to ensure that `setup_helpers` can be imported in an isolated environment.
There's a lot more that needs removing to cope with the upcoming 3.12 removal of distutils, but this is a short-term plug that moves things in the right direction.
nipy/nitime#199 added `cibuildwheel`. I could do that in a separate PR if desired.

MNT: Update build tools to work with modern pip

---

nipy/algorithms/clustering/tests/test_clustering.py

This was removed in Python 3.12.

Stop using deprecated unittest.TestCase.assert_() alias

---

nipy/labs/datasets/tests/test_converters.py

Use `nose.tools.assert_equal` instead.
Since `unittest.TestCase.assertEquals` is a deprecated alias for `unittest.TestCase.TestCase.assertEqual`, and is removed in Python 3.12, and since the `nose.tools` assertion names are apparently automagically generated from the `unittest.TestCase` assertion methods, `nose.tools.assert_equals` is also removed in Python 3.12 (when `nose` is otherwise patched to work with Python 3.12).

Don’t use nose.tools.assert_equals

---

pyproject.toml

Fixes #508 and simplifies the build logic a bit, thanks to backwards-compatible numpy builds (see https://numpy.org/doc/stable/release/1.25.0-notes.html#compiling-against-the-numpy-c-api-is-now-backwards-compatible-by-default).

MNT: Update build requirements to use numpy 1.25 and cython<3

---

nipy/labs/spatial_models/tests/test_discrete_domain.py

See:
https://github.com/nipy/nibabel/issues/1198
https://github.com/nipy/nibabel/pull/1199
https://github.com/nilearn/nilearn/pull/3649

Fix test creating unsupported double-precision GiftiDataArray

---

nipy/algorithms/statistics/formula/tests/test_formula.py
nipy/core/image/image_spaces.py
nipy/core/image/tests/test_image_spaces.py
nipy/io/tests/test_image_io.py
nipy/labs/spatial_models/parcel_io.py
nipy/labs/spatial_models/tests/test_discrete_domain.py
nipy/labs/spatial_models/tests/test_mroi.py
nipy/labs/spatial_models/tests/test_parcel_io.py
nipy/utils/compat3.py
nipy/utils/tests/test_compat3.py
tools/run_log_examples.py

Rebased from:
https://salsa.debian.org/med-team/nipy/-/blob/12a4fbea8c99c1e5dc07ee81bc3da1a450617050/debian/patches/nibabel5.0.0.patch
This is a version of https://github.com/nipy/nipy/pull/498 that applies cleanly and seems to work as expected in Fedora Linux. Please see the original PR for discussion.

Account for nibabel 5.0.0 removal of .py3k shim - use numpy.compat.py3k

---

README.rst
dev-requirements.txt
nipy/info.py

This was only needed for Python 2.7, which `nipy` will no longer support (https://github.com/nipy/nipy/pull/512#discussion_r1333271211).

Drop the PyPI mock dependency

---

setup.cfg

Fixes:
```
********************************************************************************
Usage of dash-separated doc-files will not be supported in future
versions. Please use the underscore name doc_files instead.
By 2023-Sep-26, you need to update your project and remove deprecated calls
or your builds will no longer be supported.
See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
********************************************************************************
```

Replace doc-files with doc_files in setup.cfg

---

nipy/labs/glm/glm.py
nipy/labs/spatial_models/parcel_io.py
nipy/labs/utils/reproducibility_measures.py

These comparisons against string literals may work in practice due to implementation details of string interning in CPython, but they are not reliable or correct, and they produce a `SyntaxWarning` in Python 3.12. Strings should always be compared by value (`==`/`!=`) rather than identity (`is`/`is not`).

Do not compare strings by identity (address)

---

nipy/algorithms/statistics/_quantile.pyx
nipy/labs/bindings/array.pyx
nipy/labs/bindings/linalg.pyx
nipy/labs/bindings/wrapper.pyx
nipy/labs/glm/kalman.pyx
nipy/labs/group/glm_twolevel.pyx
nipy/labs/group/onesample.pyx
nipy/labs/group/twosample.pyx
nipy/labs/utils/routines.pyx

None of these declarations was incorrect, but Cython now warns about them. The developers are worried that people will write “`cdef int* a, b`” and think that “`b`” is an “`int*`” rather than an “`int`”. Reducing the number of warnings from Cython makes it easier to notice warnings that might represent real problems.
See also https://groups.google.com/g/cython-users/c/MA8I1wmoT0Q for discussion.

Cython: declare pointers one per line

---

nipy/algorithms/statistics/formula/formulae.py
nipy/core/reference/coordinate_map.py
nipy/modalities/fmri/design.py
nipy/modalities/fmri/utils.py
nipy/utils/perlpie.py
tools/apigen.py

Escape backslashes that should be passed through to the documentation system rather than interpreted as backslash escape sequences in the Python string.
This fixes a number of `SyntaxWarning` instances about invalid escape sequences in Python 3.12.
An alternative would be to make these docstrings raw strings (`r"""foo"""`).

Fix backslash escaping issues in docstrings

---

pyproject.toml

The ruff manual recommends `requires-python` instead of `target-version` for projects using a `pyproject.toml` file:
https://docs.astral.sh/ruff/settings/#target-version
Fixes https://github.com/nipy/nipy/pull/558#discussion_r1435702572.

MNT: let ruff use `requires-python`

---

.pre-commit-config.yaml
examples/labs/need_data/demo_roi.py
pyproject.toml

Apply some [Repo-Review](https://learn.scientific-python.org/development/guides/repo-review/?repo=nipy%2Fnipy&branch=main) suggestions.
I went for the low-hanging fruits, other changes are more invasive and deserve a PR of their own, such as using a formatter like ruff of black.
* [PC190](https://learn.scientific-python.org/development/guides/style#PC190): Uses Ruff
Use `https://github.com/astral-sh/ruff-pre-commit` instead of `https://github.com/charliermarsh/ruff-pre-commit` in `.pre-commit-config.yaml`
* RF202: Use (new) lint config section
`select` should be set as `lint.select` instead
* VPP001: Validate pyproject.toml
Invalid pyproject.toml! Error: `project` must not contain {'python-requires'} properties
Also, update ruff to a decently recent version.
I have left this issue for a …

MNT: apply Repo-Review suggestions

---

lib/fff_python_wrapper/fffpy.c
nipy/algorithms/registration/cubic_spline.c
nipy/algorithms/registration/joint_histogram.c
nipy/algorithms/registration/polyaffine.c
nipy/algorithms/segmentation/mrf.c

The commit “Do not cast the result of PyArray_DATA()” is in this PR because it touches most of the same lines that needed to be touched to fix const-related warnings.
I’d like to suggest that a broader change to stop explicitly casting `void *` return values could make sense; I claim that they add clutter and repetition but don’t reduce errors. They are not required because `void *` happily converts implicitly to any data pointer type (in C, not C++). Such a change would affect at least `malloc()`, `calloc()`, `realloc()`, and `PyArray_ITER_DATA()`. However, I don’t want to get that tangled up with the const-correctness changes, especially if it’s not desired.

Improve const-correctness in C code

---

nipy/algorithms/statistics/models/model.py
nipy/algorithms/statistics/models/regression.py
nipy/core/image/image.py

Nipy has a minimum Python of 3.8, so we can use the stdlib `functools.cached_property`.

RF: nibabel.onetime.auto_attr -> functools.cached_property

---

doc/labs/viz.rst

Currently the documentation for [how to plot activation maps](https://nipy.org/nipy/labs/viz.html) throws an error when run on a clean environment:
```
TypeError: slice indices must be integers or None or have an __index__ method
```
The issue is these lines
```py
x_map, y_map, z_map = coord_transform(x, y, z, mni_sform_inv)
map = np.zeros((182, 218, 182))
map[x_map-30:x_map+30, y_map-3:y_map+3, z_map-10:z_map+10] = 1
```
`x_map` is returned as a 0 dimensional `np.array` which can't be used for indexing
The current fix is a bit of a band-aid. Would it be better to modify `coord_transform()` so that it actually returns integers?

DOC: Fix activation map tutorial
