- nipy/labs/viz_tools/coord_tools.py
- nipy/labs/viz_tools/test/test_coord_tools.py
Fix by Bertrand.
I (MB) added some refactoring and tests.
> MRG: fix to viz test error in Python 3

- Makefile
- doc/Makefile
- doc/conf.py
- doc/devel/guidelines/make_release.rst
- doc/documentation.rst
- tools/upload-gh-pages.sh
Machinery to upload docs to gh-pages.
Deprecate old sourceforge stuff.
> MRG: move doc building to use gh-pages

- .travis.yml
- nipy/info.py
- tools/travis_tools.sh
Python 3 builds broken for travis - refactor using dipy as template to get
better handle on the problem.
> MRG: refactor, fix traxis build

- LICENSE
- doc/conf.py
- doc/devel/guidelines/make_release.rst
These look like good changes that weren't merged into the current master. I had based my fix for #325 on this branch, for back compatibility purposes, and was surprised to find commits in here but not in master.
> Merge maint/0.3.x into master

- .travis.yml
- nipy/algorithms/clustering/setup.py
- nipy/labs/bindings/setup.py
- nipy/labs/glm/setup.py
- nipy/labs/group/setup.py
- nipy/labs/setup.py
- nipy/labs/utils/setup.py
- setup.cfg
Add environment variable and setup.cfg option for compiling against external
lapack.
> CONFIG: add config option for LAPACK compile

- nipy/algorithms/statistics/tests/test_utils.py
- nipy/algorithms/statistics/utils.py
> MRG: remove call to calc_lwork

- nipy/algorithms/registration/groupwise_registration.py
- nipy/algorithms/registration/tests/test_fmri_realign4d.py
- nipy/algorithms/registration/type_check.py
Following a recent discussion on the nipy list initiated by Michael Hallquist, I added docstrings to describe the arguments involved in motion estimation.
> Document 4d realignment speedup/multiscale parameters

- nipy/algorithms/registration/histogram_registration.py
- nipy/algorithms/registration/similarity_measures.py
- nipy/algorithms/registration/tests/test_histogram_registration.py
This should fix https://github.com/nipy/nipy/issues/273
> add error checking for slr similarity measure in HistogramRegistration

- examples/ds105/parallel_run.py
- examples/interfaces/process_ds105.py
Python 3 adding of ranges in one example.
Stray text in another file causing a syntax error.
> BF: fix a couple of examples

- examples/labs/need_data/localizer_glm_ar.py
I am not sure if this is the correct fix, but it's an attempted fix for
gh-370.
Bertrand - is this right?  But - why has the design matrix changed in
the number of columns?
> BF: fix design matrix size for example

- nipy/algorithms/statistics/formula/formulae.py
- nipy/modalities/fmri/design.py
- nipy/modalities/fmri/design_matrix.py
- nipy/modalities/fmri/tests/test_design.py
- nipy/modalities/fmri/tests/test_dmtx.py
Rebasing Jonathan's contrast branch.
Refactor event_design and test.
> MRG: refactor on top of contrasts branch

- Makefile
- THANKS
- doc/Makefile
- doc/_templates/layout.html
- doc/devel/guidelines/gitwash/git_links.inc
- doc/links_names.txt
- nipy/info.py
Replace with neuroimaging@python.org list
> DOC: remove references to nipy-devel list

- .gitignore
- README.rst
- doc/devel/guidelines/testing.rst
- doc/links_names.txt
> MRG: improve documentation on testing

- AUTHOR
- Changelog
- LICENSE
- doc/conf.py
- doc/devel/guidelines/make_release.rst
I would love comments / feedback on the Changelog - I wrote this
quickly.
> MRG: ready for 0.4.0 release

- examples/ds105/ds105_example.py
Some commits to fix ds105 nipy example.
> WIP: working on ds105 nipy example

- nipy/algorithms/statistics/empirical_pvalue.py
In the notes, variance and standard deviation were mixed.
> confusion variance <--> standard deviation

- nipy/algorithms/registration/tests/test_fmri_realign4d.py
> Capitalized constants

- .travis.yml
- nipy/labs/viz_tools/activation_maps.py
- nipy/labs/viz_tools/test/test_activation_maps.py
So that also anatomicals can be plotted with `interpolation='nearest'`, for example.
> ENH: pass kwargs to imshow also for plot_anat

- .travis.yml
- nipy/labs/spatial_models/mroi.py
- nipy/labs/spatial_models/tests/test_bsa.py
When iterating through feature dictionary, the hroi module was using the
dictionary keys, which are being modified inside the loop.  Use a static
list of the keys to prevent this happening.
See: https://github.com/nipy/nipy/issues/420
> BF: fix bug modifying feature dictionary of MROI

- examples/algorithms/ward_clustering.py
- examples/labs/permutation_test_fakedata.py
- nipy/algorithms/clustering/gmm.py
- nipy/algorithms/clustering/hierarchical_clustering.py
- nipy/info.py
- nipy/labs/group/permutation_test.py
- nipy/labs/statistical_mapping.py
- setup.py
gmm plot attempting reshape with float element.
> BF: fix numpy 1.12 indexing error in gmm plot

- AUTHOR
- Changelog
- LICENSE
- README.rst
- doc/conf.py
- doc/devel/guidelines/make_release.rst
- doc/users/install_data.rst
- nipy/info.py
Getting ready for 0.4.1 bugfix release.
> MAINT: updating docs for release

- .travis.yml
- nipy/algorithms/diagnostics/tsdiffplot.py
- nipy/algorithms/group/parcel_analysis.py
- nipy/algorithms/segmentation/tests/test_segmentation.py
- nipy/algorithms/statistics/formula/formulae.py
- nipy/algorithms/statistics/tests/test_intrinsic_volumes.py
- nipy/algorithms/tests/test_kernel_smooth.py
- nipy/core/image/image.py
- nipy/labs/datasets/volumes/tests/test_volume_grid.py
- nipy/modalities/fmri/hemodynamic_models.py
Use pre-release numpy / scipy wheels for testing.
> MRG: test against pre-release numpy / scipy

- nipy/algorithms/group/parcel_analysis.py
- nipy/algorithms/registration/histogram_registration.py
- nipy/algorithms/segmentation/tests/test_segmentation.py
- nipy/core/reference/tests/test_coordinate_map.py
> MRG: bug fixes for Windows

- .appveyor.yml
Set up daily builds on Appveyor.
This should be merged after:
* #435
* #436
* #437
[skip ci]
> MRG: Add appveyor file for daily build

- .appveyor.yml
- .travis.yml
- doc-requirements.txt
- nipy/algorithms/clustering/tests/test_vmm.py
- nipy/algorithms/diagnostics/tests/test_screen.py
- nipy/algorithms/statistics/formula/formulae.py
- nipy/algorithms/statistics/rft.py
- nipy/algorithms/statistics/tests/test_rft.py
- nipy/fixes/numpy/testing/nosetester.py
- nipy/info.py
- nipy/labs/group/permutation_test.py
- nipy/labs/viz_tools/test/test_activation_maps.py
- nipy/labs/viz_tools/test/test_cm.py
- nipy/labs/viz_tools/test/test_slicers.py
- nipy/modalities/fmri/tests/test_aliases.py
- nipy/testing/__init__.py
- nipy/testing/decorators.py
- nipy/tests/test_scripts.py
- requirements.txt
there you go @yarikoptic :-)
closes #456 
closes #445 
closes #452
closes #453 
closes #454 
closes #461
> FIX various fixes for deprecations in numpy, scipy, sphinx

- nipy/cli/tsdiffana.py
> Fix a typo introduced in PR#501

- nipy/algorithms/statistics/models/model.py
- nipy/algorithms/statistics/models/regression.py
- nipy/core/image/image.py
- pyproject.toml
- setup.py
> FIX: Rename setattr_on_read to auto_attr

- nipy/labs/viz_tools/cm.py
Ref: https://github.com/matplotlib/matplotlib/pull/20806/
> Replace deprecated/removed matplotlib.cm.LUTSIZE

- nipy/core/image/image_spaces.py
- nipy/core/image/tests/test_image_spaces.py
Just rephrase the cast to float
> MRG: Follow up rephrase from #512

- .github/workflows/test.yml
See #517
This is just a basic start. Once it works and it merged we can improve it.
> Add basic GH action tests

- .github/workflows/test.yml
- nipy/algorithms/clustering/tests/test_vmm.py
- nipy/algorithms/diagnostics/tests/test_screen.py
- nipy/algorithms/statistics/formula/tests/test_formula.py
- nipy/algorithms/statistics/tests/test_rft.py
- nipy/algorithms/utils/pca.py
- nipy/core/image/tests/test_image_spaces.py
- nipy/core/reference/coordinate_map.py
- nipy/core/reference/tests/test_coordinate_map.py
- nipy/externals/transforms3d/tests/test_quaternions.py
- nipy/fixes/numpy/testing/utils.py
- nipy/io/tests/test_image_io.py
- nipy/labs/spatial_models/tests/test_bsa.py
- nipy/labs/spatial_models/tests/test_discrete_domain.py
- nipy/labs/viz_tools/test/test_activation_maps.py
- nipy/modalities/fmri/fmristat/tests/test_FIAC.py
- nipy/modalities/fmri/tests/test_dmtx.py
- nipy/testing/__init__.py
- nipy/testing/decorators.py
- nipy/tests/test_scripts.py
> CI: Get tests running, some minor fixes

- .github/workflows/doc-build.yml
- doc-requirements.txt
- doc/Makefile
- doc/conf.py
- doc/users/basic_io.rst
- doc/users/math_coordmap.rst
- doc/users/plots/neuronal_event.py
Docs appear to build OK with latest Sphinx and Numpydoc
See #464
> Relax requirements for documentation tools

- AUTHOR
- Changelog
- LICENSE
- dev-requirements.txt
- doc/conf.py
- doc/devel/guidelines/make_release.rst
- examples/.gitignore
- examples/compute_fmri_contrast.py
- examples/data/README_mni_basal_ganglia.rst
- examples/ds105/ds105_util.py
- examples/fiac/fiac_util.py
- examples/labs/bayesian_structural_analysis.py
- examples/labs/group_reproducibility_analysis.py
- examples/labs/need_data/demo_blob_from_image.py
- examples/labs/need_data/demo_roi.py
- examples/labs/need_data/demo_ward_clustering.py
- examples/labs/need_data/example_roi_and_glm.py
- examples/labs/need_data/first_level_fiac.py
- examples/labs/need_data/localizer_glm_ar.py
- examples/labs/need_data/one_sample_t_test.py
- examples/labs/need_data/viz.py
- examples/labs/need_data/viz3d.py
- examples/labs/onesample_group.py
- nipy/algorithms/clustering/gmm.py
- nipy/info.py
- nipy/labs/statistical_mapping.py
Various small bugfixes and documentation updates for upcoming release.
> MRG: preparing for 0.6.0 release

- nipy/_build_utils/cythoner.py
- nipy/_build_utils/gcc_build_bitness.py
A couple of files were still shipping with a plain python shebang.
> update missing python3 shebangs.

- nipy/algorithms/clustering/hierarchical_clustering.py
- nipy/algorithms/clustering/von_mises_fisher_mixture.py
- nipy/algorithms/statistics/models/model.py
- nipy/algorithms/statistics/models/regression.py
- nipy/core/reference/coordinate_map.py
- nipy/core/reference/coordinate_system.py
- nipy/labs/spatial_models/hierarchical_parcellation.py
- nipy/labs/spatial_models/parcel_io.py
- nipy/labs/spatial_models/parcellation.py
Leave out [ISC002](https://docs.astral.sh/ruff/rules/multi-line-implicit-string-concatenation/) for now.
> Apply ruff/flake8-implicit-str-concat rules (ISC)

- .github/workflows/coverage.yml
- .github/workflows/doc-build.yml
- .github/workflows/test.yml
- pyproject.toml
Python 3.13 is not available yet in some runners, use Python 3.12 instead.
> Test on Python 3.13
